### ISSUE TITLE
No repetir

### ISSUE THREAD

**Issue by LcsGrz** [eskeltron/recipe-puzzle#1]
https://github.com/eskeltron/recipe-puzzle/blob/61e12498902921eae5eac0a2c53b321fb02030af/src/config/typeorm.ts#L12

Cuando uses muchas veces una condicion, lo mejor es crear una constante y llamarlo de ahi, ejemplo

const isProd = env === "production"

**Comment by eskeltron** [comment]
Hola!

Sí, totalmente de acuerdo.

Se me pasó por alto porque ya había pusheado el código completo al repo, pero quería hacerlo andar en Heroku también (me faltaba solamente la bbdd online) así que busque cualquiera que fuera free para realizar la demostración e hice todo a las apuradas.

Arreglado, gracias!
